apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slave2

  template:
    metadata:
      labels:
        app: slave2
    spec:
      containers:
        - name: slave2
          image: slave2
          env:
            - name: SLAVE_NAME
              value: slave2


